### ISSUE TITLE
html 좀더 가다듬기.

### ISSUE THREAD

**Issue by khw7096** [75mm-studio/estimate-onset#1]

**Comment by khw7096** [comment]
문서 제목:  Onset acquisition estimate system

**Comment by khw7096** [comment]
각 옵션에 한글도 작성할 것

**Comment by khw7096** [comment]
주의사항 추가할 것
- Estimate is validate during 30 days from reporting date.
- Please contact us directly for Overseas Travel Expense.

**Comment by khw7096** [comment]
일정은 Shooting Date 로 바꿀 것

**Comment by khw7096** [comment]
출장비는 기본 checked 상태가 되어야 한다.

**Comment by baesy0** [comment]
일정은 '프로젝트 예상기간'을 말하는 건가요?

**Comment by khw7096** [comment]
네~

**Comment by baesy0** [comment]
완료!
