### ISSUE TITLE
아이폰에서 Onset Acquisition Pricing 제목이 크게 보임.

### ISSUE THREAD

**Issue by khw7096** [75mm-studio/estimate-onset#14]

**Comment by baesy0** [comment]
https://github.com/twbs/rfs

이런 방법을 찾았어요.
일단은 더 쉬운 방법이 있을까 싶어서 다른 방법을 찾아보려구요.

**Comment by khw7096** [comment]
https://github.com/lazypic/web/blob/master/css/creative.css

```css
@media (min-width: 768px) {
}
```

뜻은 만약 768픽셀 이상이라면 무얼 해라~ 라는 뜻인데.. css에 이런 문장을 넣어주는게 더 유지보수하기 좋을 것 같아요. 위 라이브러리는 npm 의존성이 발생하네요.

**Comment by baesy0** [comment]
오호 해볼게요!
