### ISSUE TITLE
저작권 이슈 표기하기.

### ISSUE THREAD

**Issue by khw7096** [75mm-studio/estimate-onset#24]
- 라이다 데이터를 다른 회사에 사용 및 양도 할 수 없다.
- 라이다 데이터에 대한 저작권은 75미리에 있다.
- 현장 퍼밋에 대한 비용은 우리가 지불하지 않는다.

**Comment by baesy0** [comment]
a523c535dbb734139cbb08b1df1d9265cefc1ca9

**Comment by baesy0** [comment]
`현장 퍼밋`은 정확한 영어 표현을 몰라서 일단 대충 해석해놓았어요. 추후 확인이 필요합니다.
