### ISSUE TITLE
Texture(optional) 

### ISSUE THREAD

**Issue by khw7096** [75mm-studio/estimate-onset#26]
Texture(optional) -> Lidar + Texture 라고 표기하고 가격을 $10000 으로 수정하는 것이 가독성에 더 좋아보인다.

- 용빈

**Comment by baesy0** [comment]
ㅋㅋ용빈님 고마워요!

**Comment by baesy0** [comment]
`pricingCard`브랜치에서 시도해봤어요
e0182ee3a65fbc406278a96043b679e7fa91aced
저도 이 편이 더 명확한 거 같아요!

**Comment by baesy0** [comment]
ccc90e6d5aa776555729ae5c64feac988c183e0d
